version: "3"

services:
  pixelfairy-api:
    build: ./services/pixelfairy-api
    env_file:
      - ./environment/pixelfairy-api.development.env
    environment:
      - PORT=3000
    working_dir: /app
    volumes:
      - ./services/pixelfairy-api:/app
    ports:
      - 80:3000
    command: ./entrypoint.sh