apiVersion: v1
kind: Service
metadata:
  name: pixelfairy-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: pixelfairy-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelfairy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixelfairy-api
  template:
    metadata:
      labels:
        app: pixelfairy-api
    spec:
      containers:
        - name: pixelfairy-api
          image: docker.pkg.github.com/sublayerio/pixelfairy-api/pixelfairy-api:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
